### ISSUE TITLE
[New Feature] Implement YAML export during assignment

### ISSUE THREAD

**Issue by r-akemii** [AequilibraE/qaequilibrae#251]
Implement a YAML export during assignment and, then, run assignment using QGIS processing provider with a function just like https://github.com/AequilibraE/qaequilibrae/pull/250 (would take the YAML as only input).

**Comment by Art-Ev** [comment]
Have made the "processing provider" part directly in #250 : 
- Used YAML file as pyyaml already shipped with QGIS (also I think that yaml file are more userfriendly to read/edit)
- Have tried to follow the menus for organising/grouping parameters
- Will easily allow the addition of future functions (ex. link analyses)

Yaml example display in the help of the qgis process : 
```
Project: D:/AequilibraE/Project/

Run_name: sce_from_yaml

Traffic_classes:
    - car:
        matrix_path: D:/AequilibraE/Project/matrices/demand.aem
        matrix_core: car
        network_mode: c
        pce: 1
        blocked_centroid_flows: True
        skims: travel_time, distance
    - truck:
        matrix_path: D:/AequilibraE/Project/matrices/demand.aem
        matrix_core: truck
        network_mode: c
        pce: 2
        fixed_cost: toll
        vot: 12
        blocked_centroid_flows: True

Assignment:
    algorithm: bfw
    vdf: BPR2
    alpha: 0.15
    beta: power
    capacity_field: capacity
    time_field: travel_time
    max_iter: 250
    rgap: 0.0001
```
